# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2857cd0f28929ed456985ab29743e78eaf1c02b76cdcddb2799c86f5857f705b9f5b146b62c5280526622693b15992b9abfc6fe6b17c0236128c5cd35faaf1fd

test:
  secret_key_base: f258de60f11c04c5cd6cbc6a1ea945d8f7713f9199d3913b291af633b68b1d27100f50858de44758c4e4bc3d30d4eaef7b397bfcd592540d74cdd694d41bc404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
